locale: auto
avatar: ''
username: ''
theme: 'system'
themeColor: 'system'
db: null
rack:
  - type: all
    value: ''
    fold: false
autoUpdate: false
extensions: {}
updateSource: 'https://api.github.com/repos/JonnyJong/abm3/releases/latest'
updateSourceCustom: ''
# <Extension Path>:
#   enable: true
