locale: auto
avatar: ''
username: ''
theme: 'system'
themeColor: 'system'
db: null
rack:
  - type: all
    value: ''
    fold: false
autoUpdate: false
extensions: {}
# <Extension Path>:
#   enable: true
